package cards;

import static cards.Rank.*;
import static cards.Suit.*;

public enum Card {
	
	/*TWO_OF_DIAMONDS(TWO, DIAMOND),
	THREE_OF_DIAMONDS(THREE, DIAMOND),
	FOUR_OF_DIAMONDS(FOUR, DIAMOND),
	FIVE_OF_DIAMONDS(FIVE, DIAMOND),
	SIX_OF_DIAMONDS(SIX, DIAMOND),
	SEVEN_OF_DIAMONDS(SEVEN, DIAMOND),
	EIGHT_OF_DIAMONDS(EIGHT, DIAMOND),
	NINE_OF_DIAMONDS(NINE, DIAMOND),
	TEN_OF_DIAMONDS(TEN, DIAMOND),
	JACK_OF_DIAMONDS(JACK, DIAMOND),
	QUEEN_OF_DIAMONDS(QUEEN, DIAMOND),
	KING_OF_DIAMONDS(KING, DIAMOND),
	ACE_OF_DIAMONDS(ACE, DIAMOND),
	
	TWO_OF_CLUBS(TWO, CLUB),
	THREE_OF_CLUBS(THREE, CLUB),
	FOUR_OF_CLUBS(FOUR, CLUB),
	FIVE_OF_CLUBS(FIVE, CLUB),
	SIX_OF_CLUBS(SIX, CLUB),
	SEVEN_OF_CLUBS(SEVEN, CLUB),
	EIGHT_OF_CLUBS(EIGHT, CLUB),
	NINE_OF_CLUBS(NINE, CLUB),
	TEN_OF_CLUBS(TEN, CLUB),
	JACK_OF_CLUBS(JACK, CLUB),
	QUEEN_OF_CLUBS(QUEEN, CLUB),
	KING_OF_CLUBS(KING, CLUB),
	ACE_OF_CLUBS(ACE, CLUB),
	
	TWO_OF_HEARTS(TWO, HEART),
	THREE_OF_HEARTS(THREE, HEART),
	FOUR_OF_HEARTS(FOUR, HEART),
	FIVE_OF_HEARTS(FIVE, HEART),
	SIX_OF_HEARTS(SIX, HEART),
	SEVEN_OF_HEARTS(SEVEN, HEART),
	EIGHT_OF_HEARTS(EIGHT, HEART),
	NINE_OF_HEARTS(NINE, HEART),
	TEN_OF_HEARTS(TEN, HEART),
	JACK_OF_HEARTS(JACK, HEART),
	QUEEN_OF_HEARTS(QUEEN, HEART),
	KING_OF_HEARTS(KING, HEART),
	ACE_OF_HEARTS(ACE, HEART),
	
	TWO_OF_SPADES(TWO, SPADE),
	THREE_OF_SPADES(THREE, SPADE),
	FOUR_OF_SPADES(FOUR, SPADE),
	FIVE_OF_SPADES(FIVE, SPADE),
	SIX_OF_SPADES(SIX, SPADE),
	SEVEN_OF_SPADES(SEVEN, SPADE),
	EIGHT_OF_SPADES(EIGHT, SPADE),
	NINE_OF_SPADES(NINE, SPADE),
	TEN_OF_SPADES(TEN, SPADE),
	JACK_OF_SPADES(JACK, SPADE),
	QUEEN_OF_SPADES(QUEEN, SPADE),
	KING_OF_SPADES(KING, SPADE),
	ACE_OF_SPADES(ACE, SPADE);*/
	
	TWO_D(TWO, DIAMOND, "2d"),
	THREE_D(THREE, DIAMOND, "3d"),
	FOUR_D(FOUR, DIAMOND, "4d"),
	FIVE_D(FIVE, DIAMOND, "5d"),
	SIX_D(SIX, DIAMOND, "6d"),
	SEVEN_D(SEVEN, DIAMOND, "7d"),
	EIGHT_D(EIGHT, DIAMOND, "8d"),
	NINE_D(NINE, DIAMOND, "9d"),
	Td(TEN, DIAMOND),
	Jd(JACK, DIAMOND),
	Qd(QUEEN, DIAMOND),
	Kd(KING, DIAMOND),
	Ad(ACE, DIAMOND),
	
	TWO_H(TWO, HEART, "2h"),
	THREE_H(THREE, HEART, "3h"),
	FOUR_H(FOUR, HEART, "4h"),
	FIVE_H(FIVE, HEART, "5h"),
	SIX_H(SIX, HEART, "6h"),
	SEVEN_H(SEVEN, HEART, "7h"),
	EIGHT_H(EIGHT, HEART, "8h"),
	NINE_H(NINE, HEART, "9h"),
	Th(TEN, HEART),
	Jh(JACK, HEART),
	Qh(QUEEN, HEART),
	Kh(KING, HEART),
	Ah(ACE, HEART),
	
	TWO_C(TWO, CLUB, "2c"),
	THREE_C(THREE, CLUB, "3c"),
	FOUR_C(FOUR, CLUB, "4c"),
	FIVE_C(FIVE, CLUB, "5c"),
	SIX_C(SIX, CLUB, "6c"),
	SEVEN_C(SEVEN, CLUB, "7c"),
	EIGHT_C(EIGHT, CLUB, "8c"),
	NINE_C(NINE, CLUB, "9c"),
	Tc(TEN, CLUB),
	Jc(JACK, CLUB),
	Qc(QUEEN, CLUB),
	Kc(KING, CLUB),
	Ac(ACE, CLUB),
	
	TWO_S(TWO, SPADE, "2s"),
	THREE_S(THREE, SPADE, "3s"),
	FOUR_S(FOUR, SPADE, "4s"),
	FIVE_S(FIVE, SPADE, "5s"),
	SIX_S(SIX, SPADE, "6s"),
	SEVEN_S(SEVEN, SPADE, "7s"),
	EIGHT_S(EIGHT, SPADE, "8s"),
	NINE_S(NINE, SPADE, "9s"),
	Ts(TEN, SPADE),
	Js(JACK, SPADE),
	Qs(QUEEN, SPADE),
	Ks(KING, SPADE),
	As(ACE, SPADE);
	
	private Rank rank;
	private Suit suit;
	private String display;
	
	private Card(Rank rank, Suit suit) {
	
		this(rank, suit, null);
	}
	
	private Card(Rank rank, Suit suit, String display) {
		
		this.rank = rank;
		this.suit = suit;
		this.display = display;
	}
	
	public Rank rank() {
		return rank;
	}
	
	public Suit suit() {
		return suit;
	}
	
	public String toString() {
		return (display == null) ? super.toString() : display;
	}

}
